CREATE DATABASE CURSOS
GO

USE CURSOS

CREATE TABLE TB_USUARIOS
						(
						Codigo INT IDENTITY PRIMARY KEY
						,Login VARCHAR(15)
						,Email VARCHAR(Max)
						,Senha VARCHAR(Max)
						)
GO

CREATE TABLE TB_CURSOS
					(
					Codigo INT IDENTITY PRIMARY KEY
					,Nome VARCHAR(Max)
					,Descricao VARCHAR(Max)
					,CodigoUsuario INT 
					)
ALTER TABLE TB_CURSOS ADD CONSTRAINT FK_USUARIO_CODUSUARIO FOREIGN KEY (CodigoUsuario) REFERENCES TB_USUARIOS (Codigo)
GO